### PR TITLE
Add install target

### PR DESCRIPTION
**Pull request by lukeyeager**
CMake provides a `make install` target by default. Simply run these two commands to make and install to `/usr/local`:
```
make && sudo make install
```
NOTE: don't merge this without merging #42! Otherwise the build (and tests) will have to run twice and will run as root the second time.

### CODE REVIEW

**Comment by sickill** [comment]
Thx! And happy new year! :tada:

**Comment by sickill** [comment]
Oops, looks like we have a conflict here.

**Comment by lukeyeager** [comment]
> Oops, looks like we have a conflict here.

Rebased.

**Comment by sickill** [comment]
@lukeyeager thanks!

**Pull request merged**
